title: ClickUp4Java
description: Documentation for ClickUp4Java
theme: minima

# IMPORTANTE: como o site vai ser /ClickUp4Java/
baseurl: "/ClickUp4Java"
url: "https://lucasalexandrebez.github.io"

markdown: kramdown
